"""
VPS Setup Script — first-time setup for the MT5 Gateway on a Windows VPS.

Run this once after deploying the code to the VPS:
    python scripts/setup_vps.py

It will:
1. Create required directories
2. Generate encryption key if not set
3. Validate MT5 template installation
4. Create .env file from template
5. Install Python dependencies
6. Set up firewall rules
"""

import os
import sys
import subprocess
import shutil


def main():
    print("=" * 60)
    print("  MT5 Gateway — VPS Setup")
    print("=" * 60)

    project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(project_dir)

    # 1. Create directories
    print("\n[1/6] Creating directories...")
    dirs = [
        "data",
        "logs",
        r"C:\MT5_INSTANCES",
    ]
    for d in dirs:
        os.makedirs(d, exist_ok=True)
        print(f"  ✓ {d}")

    # 2. Generate encryption key
    print("\n[2/6] Encryption key...")
    from cryptography.fernet import Fernet
    key = Fernet.generate_key().decode()
    print(f"  Generated key: {key}")
    print("  Add this to your .env as GATEWAY_ENCRYPTION_KEY")

    # 3. Check MT5 template
    print("\n[3/6] Checking MT5 template...")
    template_paths = [
        r"C:\MT5Template",
        r"C:\Program Files\MetaTrader 5",
        r"C:\Program Files (x86)\MetaTrader 5",
    ]
    found_template = None
    for path in template_paths:
        exe = os.path.join(path, "terminal64.exe")
        if os.path.exists(exe):
            found_template = path
            print(f"  ✓ Found MT5 at: {path}")
            break

    if not found_template:
        print("  ✗ MT5 template not found!")
        print("    Install MetaTrader 5 to C:\\MT5Template")
        print("    Or set GATEWAY_MT5_TEMPLATE_PATH in .env")
    else:
        # Ensure portable marker exists in template
        portable = os.path.join(found_template, "portable")
        if not os.path.exists(portable):
            with open(portable, "w") as f:
                f.write("")
            print(f"  ✓ Created portable marker in template")

    # 4. Create .env if not exists
    print("\n[4/6] Environment file...")
    env_file = os.path.join(project_dir, ".env")
    if not os.path.exists(env_file):
        import secrets
        api_key = secrets.token_urlsafe(48)
        env_content = f"""# MT5 Gateway Configuration
# Generated by setup_vps.py

# Security (REQUIRED for production)
GATEWAY_PRODUCTION=true
GATEWAY_API_KEY={api_key}
GATEWAY_ENCRYPTION_KEY={key}
GATEWAY_ALLOWED_IPS=

# Server
GATEWAY_HOST=0.0.0.0
GATEWAY_PORT=5000

# MT5 Paths
GATEWAY_MT5_BASE_PATH=C:\\MT5_INSTANCES
GATEWAY_MT5_TEMPLATE_PATH={found_template or 'C:\\MT5Template'}

# Health Check
GATEWAY_HEALTH_CHECK_INTERVAL=30
GATEWAY_MAX_RESTART_ATTEMPTS=3
GATEWAY_RESTART_COOLDOWN=60
"""
        with open(env_file, "w") as f:
            f.write(env_content)
        print(f"  ✓ Created .env with generated API key")
        print(f"  API Key: {api_key}")
    else:
        print(f"  ✓ .env already exists")

    # 5. Install dependencies
    print("\n[5/6] Installing Python dependencies...")
    try:
        subprocess.run(
            [sys.executable, "-m", "pip", "install", "-r", "requirements.txt"],
            check=True,
        )
        print("  ✓ Dependencies installed")
    except subprocess.CalledProcessError:
        print("  ✗ Failed to install dependencies")

    # Install MetaTrader5 package (Windows only)
    if sys.platform == "win32":
        try:
            subprocess.run(
                [sys.executable, "-m", "pip", "install", "MetaTrader5"],
                check=True,
            )
            print("  ✓ MetaTrader5 package installed")
        except subprocess.CalledProcessError:
            print("  ✗ Failed to install MetaTrader5 package")

    # 6. Firewall rule
    print("\n[6/6] Firewall...")
    if sys.platform == "win32":
        try:
            subprocess.run(
                [
                    "netsh", "advfirewall", "firewall", "add", "rule",
                    "name=MT5 Gateway",
                    "dir=in",
                    "action=allow",
                    "protocol=TCP",
                    "localport=5000",
                ],
                check=True,
                capture_output=True,
            )
            print("  ✓ Firewall rule added (port 5000)")
        except Exception:
            print("  ⚠ Could not add firewall rule (run as Administrator)")
    else:
        print("  ⚠ Skipped (not Windows)")

    print("\n" + "=" * 60)
    print("  Setup complete!")
    print("=" * 60)
    print(f"\nStart the gateway:")
    print(f"  python main.py")
    print(f"\nOr install as Windows service:")
    print(f"  python scripts/install_service.py install")
    print(f"  python scripts/install_service.py start")


if __name__ == "__main__":
    main()
